# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('date_done', models.DateField(auto_now=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=32)),
                ('server_stats', models.PositiveSmallIntegerField()),
                ('backup_stats', models.PositiveSmallIntegerField()),
                ('remark', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=128)),
                ('role', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
