# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='backup_stats',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u6545\u969c')]),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='server_stats',
            field=models.PositiveSmallIntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u6545\u969c')]),
        ),
    ]
