# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-22 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hd_daily', '0003_auto_20180522_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='remark',
            field=models.TextField(default=''),
        ),
    ]
